services:
  postgres:
    image: postgres:16
    container_name: utcctp-postgres
    environment:
      POSTGRES_DB: utcctp
      POSTGRES_USER: utcctp
      POSTGRES_PASSWORD: utcctp
    ports:
      - "5432:5432"
    volumes:
      - utcctp_pgdata:/var/lib/postgresql/data

volumes:
  utcctp_pgdata:
